version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
farmersdelight = true
enhanced_enchanting = true
create_easy_structures = true
alexsmobs = true
lendersdelight = true
cataclysm = true
quark = true
refurbished_furniture = true
copycats = true
citadel = true
createdieselgenerators = true
create_sa = true
railways = true
bellsandwhistles = true
amendments = true
moonlight = true
block_factorys_bosses = true
chisel = true
sophisticatedbackpacks = true
offroad = true
compatdelight = true
supplementaries = true
endrem = true
create = true
aeronautics = true
decocraft = true
interiors = true
simulated = true
aquaculture = true
legendarysurvivaloverhaul = true
sereneseasons = true
minecraft = true
create_dragons_plus = true
displaydelight = true
iceandfire = true
createdeco = true
regions_unexplored = true
create_jetpack = true
create_things_and_misc = true
createaddition = true
butchery = true
aquaculturedelight = true
sliceanddice = true
ars_nouveau = true
vinery = true
pipez = true
create_aquatic_ambitions = true
enchantinginfuser = true
