name = "DRX - Reforged"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3566bd83a9358cd264ad731a39b067b21fd9610ef73ca6f1888aabe7c46cc11c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
