name = "DRX - Reforged"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da4dc06701ae3850fc85a81fe97cf8323b59f4de63aab745946c9ee5f0d8bf3b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
